[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
GroverAlgorithm = "480f6047-bde0-43c5-a5a8-f20cfea8349f"

[sources]
GroverAlgorithm = {path = ".."}
